version: '3'

services:
  country:
    container_name: country
    build:
      context: ./lab3-country

  continent:
    container_name: continent
    build:
      context: ./lab3-continent

  gateway:
    container_name: gateway
    build:
      context: ./lab3-gateway

  frontend:
    container_name: frontend
    build:
      context: ./frontend

  proxy:
    container_name: proxy
    build:
      context: ./proxy
    ports:
      - 80:80