version: '3'

services:
  lab3-country:
    build:
      context: ./lab3-country
    networks:
      mynet:
        ipv4_address: 172.28.0.6

  lab3-continent:
    build:
      context: ./lab3-continent
    depends_on:
      - lab3-country
    networks:
      mynet:
        ipv4_address: 172.28.0.5

  lab3-gateway:
    build:
      context: ./lab3-gateway
    depends_on:
      - lab3-country
      - lab3-continent
    networks:
      mynet:
        ipv4_address: 172.28.0.4

  javascript:
    build:
      context: ./frontend
    depends_on:
      - lab3-gateway
    networks:
      mynet:
        ipv4_address: 172.28.0.3

  proxy:
    build:
      context: ./proxy
    ports:
      - 80:80
    depends_on:
      - javascript
    networks:
      mynet:
        ipv4_address: 172.28.0.2
    tty: true

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16